maykinmedia/open-klant

- INSTALL.rst
- README.rst
- docs/install/dev.rst
- package.json
- src/openklant/conf/api.py
- src/openklant/utils/context_processors.py
I'm not 100% if I got all references that use the repository or cloned directory name (which also changed from `openklant` to `open-klant`)
> Updated docs and URLs to use new Github location

- src/openklant/components/klantinteracties/api/serializers/actoren.py
- src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
- src/openklant/components/klantinteracties/api/serializers/internetaken.py
- src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
- src/openklant/components/klantinteracties/api/serializers/partijen.py
- src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
- src/openklant/components/klantinteracties/api/tests/test_partijen.py
- src/openklant/components/klantinteracties/api/validators.py
Removed every reverse lookup field in the update and create calls except digitale_adressen for easy configuration combined with voorkeurs_digitaal_adres
> :art: removed the reverse lookup fields for the create and update

- src/openklant/components/klantinteracties/admin/klantcontacten.py
- src/openklant/components/klantinteracties/admin/partijen.py
- src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
- src/openklant/components/klantinteracties/api/serializers/partijen.py
- src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
- src/openklant/components/klantinteracties/api/tests/test_partijen.py
- src/openklant/components/klantinteracties/models/klantcontacten.py
- src/openklant/components/klantinteracties/models/mixins.py
fixes #83 
added read_only volledige naam field to serializer:
- BetrokkeneSerializer
- ContactpersoonSerializer
- PersoonSerializer
> :sparkles: [#83] added read_only volledige naam

- src/openklant/components/klantinteracties/api/filterset/partijen.py
- src/openklant/components/klantinteracties/api/tests/test_filters.py
fixes #154 
added filter for categorie naam on partij enpoint
> :sparkles: [#154] add categorie filter on partij

- src/openklant/components/klantinteracties/api/tests/test_expand.py
- src/openklant/components/klantinteracties/openapi.yaml
- src/openklant/components/utils/expansion.py
- src/openklant/utils/converters.py
- src/openklant/utils/tests/test_converters.py
Fixes #165 
- Changed the query param values for the expand from snake_case to camelCase
- added snake_case to camelCase converter
- added camelCase to snake_case converter
> :art: [#165] changed expand snake_case query params to camelCase

- src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
- src/openklant/components/klantinteracties/api/tests/test_filters.py
- src/openklant/components/klantinteracties/openapi.yaml
fixes #146 
added onderwerpobject filters on klantcontact:
- onderwerpobject__uuid
- onderwerpobject__url
- onderwerpobject__objectidentificator_objecttype
- onderwerpobject__objectidentificator_soort_object_id
- onderwerpobject__objectidentificator_object_id
- onderwerpobject__objectidentificator_register
> :sparkles: [#146] added onderwerpobject filters on klantcontact endpoint

- .github/workflows/ci.yml
Fixes #179
To be honest I couldn't find why uploading results to code scanning stopped working on 15.03.24. The config looks the same as in Open Zaak
What I did:
* removed unnecessary step in the image-scan job
* updated version of gh action to upload trivy report
* force tests to run and docker image to build if the action is run manually even if python files have not been changed
I want the PR to be merged to see if the changes were enough
> fix Trivy action

- src/openklant/templates/index.html
- src/openklant/templates/master.html
> :memo:[#196] remove links to outdated VNG documentation

- .bumpversion.cfg
- CHANGELOG.rst
- README.rst
- package-lock.json
- package.json
- src/openklant/__init__.py
Fixes #198
Anything missing from the changelog?
> :bookmark: Release 2.1.0

- Dockerfile
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/scss/admin/_admin_theme.scss
- src/openklant/templates/admin/base_site.html
- src/openklant/utils/context_processors.py
Partially fixes https://github.com/maykinmedia/open-api-framework/issues/21
**Changes**
Shows the current version of the application in the admin:
> [#21] display version in admin

- src/openklant/components/klantinteracties/admin/partijen.py
- src/openklant/components/klantinteracties/api/filterset/digitaal_adres.py
- src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
- src/openklant/components/klantinteracties/api/viewsets/digitaal_adres.py
- src/openklant/components/klantinteracties/openapi.yaml
- src/openklant/conf/dev.py
Fixes #214
**Changes**
Added expand feature to digitaleadressen:
- betrokkenen
- klantcontact
- internetaken
> :sparkles: [#214] added expand to digitaal adress serializer

- src/openklant/components/klantinteracties/api/filterset/actoren.py
- src/openklant/components/klantinteracties/api/filterset/digitaal_adres.py
- src/openklant/components/klantinteracties/api/filterset/internetaken.py
- src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
- src/openklant/components/klantinteracties/api/filterset/partijen.py
- src/openklant/components/klantinteracties/api/tests/test_filters.py
- src/openklant/components/klantinteracties/api/viewsets/digitaal_adres.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #209
**Changes**
- Added punctuation to help_texts.
- Added these queryparams (except page):
> :sparkles: [#209] added queryparams to digitaaladres

- .github/workflows/ci.yml
- keycloak/data/test-realm.json
- keycloak/docker-compose.keycloak.yml
- package-lock.json
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/test-tools.in
- src/openklant/accounts/tests/factories.py
- src/openklant/accounts/tests/keycloak_cassets/duplicate_email.yaml
- src/openklant/accounts/tests/keycloak_cassets/happy_flow.yaml
- src/openklant/accounts/tests/keycloak_cassets/happy_flow_existing_user.yaml
- src/openklant/accounts/tests/test_oidc.py
- src/openklant/urls.py
- src/openklant/utils/tests/keycloak.py
Fixes [#50](https://github.com/maykinmedia/open-api-framework/issues/50)
**Changes**
updated libraries:
- ape-pie `0.1.0` to `0.2.0`
- cbor2 `5.6.3` to `5.6.4`
- certifi `2020.2.2` to `2023.7.22`
- commonground-api-common `1.13.0` to `1.13.2`
- cryptography `42.0.5` to `43.0.0`
- django `4.2.11` to `4.2.14`
- django-axes `6.4.0` to `6.5.1`
- django-cors-headers `4.3.1` to `4.4.0`
- django-otp `1.5.0` to `1.5.1`
- django-setup-configuration `0.1.0` to `0.3.0`
- django-simple-certmanager `2.0.0` to `2.3.0`
- django-solo `2.2.0` to `2.3.0`
- djangorestframework `3.15.1` to `3.15.2`
- drf-nested-routers `0.93.5` to `0.94.1`
- ecs-logging `2.1.0` to `2.2.0`
- elastic-apm `6.22.0` to `6.23.0`
- humanize `4.9.0` to `4.10.0`
- elastic-apm `6.22.0` to `6.23.0`
- jinja2 `3.1.3` to `3.1.4`
- …
> :arrow_up: [#50] updating dependecies and added oidc tests

- .github/workflows/ci.yml
- bin/generate_envvar_docs.sh
- docs/index.rst
- docs/installation/config.rst
- docs/installation/index.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/templates/open_api_framework/env_config.rst
Fixes https://github.com/open-zaak/open-zaak/issues/1649 partially
**Changes**
* Document the envvars
* Add CI job to check if envvar docs were updated
> 📝 [open-zaak/open-zaak#1649] Document envvars

- src/openklant/conf/base.py
- src/openklant/fixtures/default_admin_index.json
Fixes https://github.com/maykinmedia/open-api-framework/issues/40 partially
**Changes**
* Uninstall the django.contrib.sites app to ensure that we no longer rely on in when generating the label for 2FA
> :wrench: [maykinmedia/open-api-framework#40] Remove sites dependency

- .bumpversion.cfg
- CHANGELOG.rst
- README.rst
- package-lock.json
- package.json
- src/openklant/__init__.py
Updated open-klant from version 2.1.0 to 2.2.0
> :bookmark: release 2.2.0

- src/openklant/conf/base.py
Fixes the `CSP_EXCLUDE_URL_PREFIXES` not being set properly.
Encountered when running `makemigrations`:
```
Traceback (most recent call last):
File "/home/sonny/development/open-klant/./src/manage.py", line 24, in <module>
execute_from_command_line(sys.argv)
File "/home/sonny/development/open-klant/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute()
File "/home/sonny/development/open-klant/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
settings.INSTALLED_APPS
File "/home/sonny/development/open-klant/env/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
self._setup(name)
File "/home/sonny/development/open-klant/env/lib/python3.11/site-packages/ …
```
> Set initial `CSP_EXCLUDE_URL_PREFIXES` value in `base.py`

- src/openklant/components/contactgegevens/api/schema.py
- src/openklant/components/contactgegevens/openapi.yaml
- src/openklant/components/klantinteracties/api/schema.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #248 
**Changes**
* Use correct API root in redoc OAS view
> :memo: [#248] Use correct API root in redoc OAS view

- .bumpversion.cfg
- .github/workflows/ci.yml
- CHANGELOG.rst
- README.rst
- package.json
- src/openklant/__init__.py
Fixes  maykinmedia/open-api-framework#80 (Open-Klant part)
> :bookmark: release 2.3.0

- src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
- src/openklant/components/klantinteracties/api/serializers/partijen.py
- src/openklant/components/klantinteracties/api/tests/factories.py
- src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
- src/openklant/components/klantinteracties/api/urls.py
- src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #147
**Changes**
* Convenience endpoint for Klantcontact/Betrokkene/Onderwerpobject
* Fix incorrect viewname for onderwerpobject URL attribute
* Add typehints to remove redoc warnings
* Fix tests not running in CI due to changed-files action
> ✨ [#147] Convenience endpoint for Klantcontact/Betrokkene/Onderwerpobject

- src/openklant/components/klantinteracties/admin/klantcontacten.py
> :recycle:[#261] change Onderwerpobject inline to use klantcontact

- src/openklant/components/klantinteracties/admin/digitaal_adres.py
- src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
- src/openklant/components/klantinteracties/api/tests/test_digitaal_adres.py
- src/openklant/components/klantinteracties/api/validators.py
- src/openklant/components/klantinteracties/tests/test_admin.py
- src/openklant/utils/serializers.py
Fixes #234 
**Changes**
*  Validate DigitaalAdres.adres if type is email
>  ✨ [#234] Validate DigitaalAdres.adres if type is email

- src/openklant/components/klantinteracties/api/tests/test_partijen.py
- src/openklant/components/utils/expansion.py
Fixes #243 
**Changes**
Shows given expand query parameter results even when these are empty or `null`.
> [#243] Fix expand query parameter

- src/openklant/components/klantinteracties/admin/actoren.py
- src/openklant/components/klantinteracties/admin/internetaken.py
- src/openklant/components/klantinteracties/tests/test_admin.py
Fixes #251
**Changes**
- Added inline tabular admin for the `InterneTaakAdmin` and `ActorAdmin` to display the connection between eachother.
- Added search field for InterneTaakAdmin so that it is easier to search for a InterneTaak within the actor admin and InterneTaakAdmin.
- Added tests for  `InterneTaakAdmin` and `ActorAdmin`
> Added InterneTakenActoren to the admin

- src/openklant/components/klantinteracties/api/filterset/digitaal_adres.py
- src/openklant/components/klantinteracties/api/tests/test_filters.py
Fixes #265 
**Changes**
Add `field_name="adres"` in `DigitaalAdresFilterSet` + some tests
> [#265] Fix adres__icontains + tests

- src/openklant/components/contactgegevens/api/serializers.py
- src/openklant/components/contactgegevens/api/tests/test_apis.py
- src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
- src/openklant/components/klantinteracties/api/serializers/partijen.py
- src/openklant/components/klantinteracties/api/serializers/rekeningnummers.py
- src/openklant/components/klantinteracties/api/tests/test_actoren.py
- src/openklant/components/klantinteracties/api/tests/test_digitaal_adres.py
- src/openklant/components/klantinteracties/api/tests/test_internetaken.py
- src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
- src/openklant/components/klantinteracties/api/tests/test_partijen.py
- src/openklant/components/klantinteracties/api/tests/test_rekeningnummers.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #254
**Changes**
Changed the view_name of the `PersoonSerializer` and `BijlageSerializer` to their own detail page
> Fixed url fields urls.

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/components/klantinteracties/openapi.yaml
Partially fixes https://github.com/maykinmedia/open-api-framework/issues/66
> [#66] update zgw-consumers

- docker/setup_configuration/data.yaml
- docs/installation/setup_configuration.rst
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/conf/base.py
Fixes #294 
**Changes**
Allows users to configure mozilla-django-oidc-db through django-setup-configuration.
> [#294] add django-setup-configuration support for mozilla-django-oidc-db

- docs/installation/setup_configuration.rst
Fixes the django-setup-configuration documentation
**Changes**
Shows the correct key to use in the configuration example file, see [test file ](https://github.com/maykinmedia/open-klant/commit/f05f3a31a2e164bf15153d116cc3a7442dbc6abe#diff-fc1f1bee7f49becd30664b40c0598909e2f013a86f84525dcc2ca5ecef91c237R3)for an example.
> Update configuration example

- docker/setup_configuration/data.yaml
- docs/installation/setup_configuration.rst
- src/openklant/setup_configuration/models.py
- src/openklant/setup_configuration/steps.py
- src/openklant/setup_configuration/tests/files/token_all_fields.yaml
- src/openklant/setup_configuration/tests/files/token_empty_database.yaml
- src/openklant/setup_configuration/tests/files/token_existing_tokens.yaml
- src/openklant/setup_configuration/tests/files/token_idempotent.yaml
- src/openklant/setup_configuration/tests/files/token_invalid_email.yaml
- src/openklant/setup_configuration/tests/files/token_invalid_identifier.yaml
- src/openklant/setup_configuration/tests/files/token_invalid_token.yaml
Fixes #293 
**Changes**
Renames the configuration file namespaces for token configuration
> [#293] update token configuration file namespaces

- .github/workflows/ci.yml
- .github/workflows/code-analysis.yml
- docs/conf.py
- docs/installation/config.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
Fixes maykinmedia/open-api-framework#92 partially
**Changes**
* Make sure docs are built in CI
> :construction_worker: [maykinmedia/open-api-framework#92] Make sure docs are built in CI

- src/openklant/components/klantinteracties/admin/actoren.py
- src/openklant/components/klantinteracties/admin/digitaal_adres.py
- src/openklant/components/klantinteracties/admin/internetaken.py
- src/openklant/components/klantinteracties/admin/klantcontacten.py
Fixes #
**Changes**
Looking up objects based on their UUID and/or fetching a UUID from a record in the admin is a common practice (e.g. because you need to match something from your logs, or match an object between systems). The UUID is also the primary key. Both are good reasons to include it in the admin field display / search fields.
> Add UUID to admin search fields and fieldsets

- bin/celery_worker.sh
Done as part of https://github.com/maykinmedia/charts/issues/165
> :fire: Remove unused command line args

- .bumpversion.cfg
- CHANGELOG.rst
- README.rst
- docs/changelog.rst
- docs/conf.py
- docs/index.rst
- package-lock.json
- package.json
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/__init__.py
- src/openklant/components/contactgegevens/openapi.yaml
- src/openklant/components/klantinteracties/openapi.yaml
- src/openklant/conf/api.py
> :bookmark: Release 2.6.0

- .bumpversion.cfg
Noticed that `bin/bump-my-version.sh` was not bumping the version of package.json/package-lock.json
> :wrench: Fix bump-my-version for package/package-lock.json

- docs/installation/config/env_configuration.rst
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- src/openklant/components/contactgegevens/api/schema.py
- src/openklant/components/contactgegevens/openapi.yaml
- src/openklant/components/klantinteracties/admin/partijen.py
- src/openklant/components/klantinteracties/api/schema.py
- src/openklant/components/klantinteracties/api/serializers/partijen.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_categorie.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_partij_identificator.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_vertegenwoordigden.py
- src/openklant/components/klantinteracties/api/tests/test_partijen.py
- src/openklant/components/klantinteracties/api/viewsets/partijen.py
- src/openklant/components/klantinteracties/models/tests/factories/partijen.py
- src/openklant/components/klantinteracties/models/validators.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #239 
**Atomicity in Partij and PartijIdentificator**
The Partij endpoint handles PartijIdentificator objects more effectively, allowing them to be processed within the same request. This ensures that both entities are handled atomically, preventing incompleteness, and offering better control over the uniqueness of PartijIdentificator objects.
For POST, PATCH, and PUT requests for Partij, it is possible to send a list of PartijIdentificator objects.
Handles `partijIdentificatoren` creation with atomicity guarantees.
- If the `UUID` is provided in the `PartijIdentificator` object,  the endpoint will treat it as an update operation for the existing `PartijIdentificator`, applying the provided data and linking the parent `Partij` to the new one created.
- If the `UUID` is **not** …
> [#239] Include PartijIdentificatoren on Partij serializer

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.in
- requirements/dev.txt
- src/openklant/conf/dev.py
- src/openklant/urls.py
I noticed that some endpoints are missing prefetch_related/select_related, resulting in a lot of queries, django-silk can be used to spot this by setting the envvar `PROFILE=yes` and navigating to `/silk` after performing requests
> :heavy_plus_sign: Add django-silk for performance profiling

- src/openklant/components/klantinteracties/api/serializers/internetaken.py
- src/openklant/components/klantinteracties/api/viewsets/actoren.py
- src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
- src/openklant/components/klantinteracties/api/viewsets/partijen.py
Fixes #385 
- Fixed, add `prefetch_related("actorklantcontact_set")`
- 2 query for list, 4 join
- ok
- 1 query for list, 2 join
- ok
- 2 query for list, 2 join
- ok
- 1 query for list, 1 join
- ok
- 1 query for list, 2 join
- ok
- 2 query for list, 0 join
- ok
- 1 query for list, 2 join
- Fixed `to_representation` method 
- 2 query for list + `klantinteracties_internetakenactorenthoughmodel` queries
- ok
- 6 query for list + `klantinteracties_medewerker` + `klantinteracties_actor` queries
- ok
- 1 query for list, 2 join
- Fixed `select_related`
- 1 query for list, 2 join
- Fixed `prefetch_related` and `select_related`
- 7 query for list, 5 join
- ok
- 1 query for list, 1 join
- ok
- 1 query for list, 2 join
- only POST
> :zap: [#385] Fix prefetch_related and select_related in queryset endpoints

- src/openklant/components/klantinteracties/openapi.yaml
- src/openklant/utils/tests/test_validators.py
- src/openklant/utils/validators.py
Fixes #368
Changes 
- ensures international format has exactly 9 digits after country code
> :bug: [#368] Fix Open Klant accepteert ongeldige telefoonnummers

- src/openklant/components/klantinteracties/admin/partijen.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py
- src/openklant/components/klantinteracties/models/partijen.py
- src/openklant/components/klantinteracties/tests/test_admin.py
Fixes #378 
**Changes**
- Improved validation of the admin form as it was done before (using reference to related objects).
- And added a new validation: because the data `voorkeurs_digitaal_adres` and `voorkeurs_rekeningnummer`, should be added after the creation of `partij (instance)`, otherwise the relationships don't exist.
- Simplified `partij.__str__()`
> :zap: [#378] Improve performance partij admin

- src/openklant/components/klantinteracties/api/polymorphism.py
- src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py
- src/openklant/components/klantinteracties/api/tests/test_notifications.py
Fixes #345  and #303
- Update the Discriminator to support `required` option
> [#345] Fix soortPartij in Partij requests

- src/openklant/utils/tests/test_validators.py
- src/openklant/utils/validators.py
Fixes #470 
**Changes**
Change the countrycode validation message to warn the user if their countrycode is in the incorrect case.
> :safety_vest: warn users if landcode is correct but lowercase

- src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
- src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
- src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
- src/openklant/components/klantinteracties/openapi.yaml
Fixes #419 
**Changes**
- adds was_klantcontact__uuid & was_klantcontact__url filters to onderwerpobjecten API.
> :sparkles: [#419] add was_klantcontact filter to onderwerpobjecten API

- src/openklant/components/klantinteracties/admin/actoren.py
- src/openklant/components/klantinteracties/admin/internetaken.py
- src/openklant/components/klantinteracties/admin/klantcontacten.py
- src/openklant/components/klantinteracties/admin/partijen.py
- src/openklant/components/klantinteracties/tests/test_admin.py
- src/openklant/fixtures/default_admin_index.json
and other admin pages that were missing this as well, to make sure the admin still loads fast if there are a lot of possible options for related objects
Fixes #510 
**Changes**
* Add missing raw_id_fields for PartijAdmin and other admin pages
> :bug: [#510] Add missing raw_id_fields for PartijAdmin
