maykinmedia/open-klant

src/openklant/components/contactmomenten/admin.py
src/openklant/components/contactmomenten/api/filters.py
src/openklant/components/contactmomenten/api/tests/test_contactmoment.py
src/openklant/components/contactmomenten/api/viewsets.py
src/openklant/components/contactmomenten/openapi.yaml
src/openklant/components/contactmomenten/swagger2.0.json
src/openklant/components/klanten/admin.py
src/openklant/components/klanten/tests/test_audittrails.py
src/openklant/conf/base.py
src/openklant/urls.py

Contactmoment list `klant` and `object` filter

---

src/openklant/components/contactmomenten/api/filters.py
src/openklant/components/contactmomenten/api/tests/test_contactmoment.py
src/openklant/components/contactmomenten/openapi.yaml
src/openklant/components/contactmomenten/swagger2.0.json

#164 medewerkerIdentificatie filters on Contactmoment list

---

src/openklant/components/contactmomenten/api/filters.py
src/openklant/components/contactmomenten/api/serializers.py
src/openklant/components/contactmomenten/api/tests/test_contactmoment.py
src/openklant/components/contactmomenten/api/viewsets.py
src/openklant/components/contactmomenten/openapi.yaml
src/openklant/components/contactmomenten/resources.md
src/openklant/components/contactmomenten/swagger2.0.json
src/openklant/components/klanten/api/viewsets.py
src/openklant/utils/filters.py
src/openklant/utils/serializers.py

#168 Contactmomenten expand parameter

---

src/openklant/components/contactmomenten/api/filters.py
src/openklant/components/contactmomenten/api/schema.py
src/openklant/components/contactmomenten/api/serializers.py
src/openklant/components/contactmomenten/api/viewsets.py
src/openklant/components/contactmomenten/openapi.yaml
src/openklant/components/contactmomenten/resources.md
src/openklant/components/contactmomenten/swagger2.0.json
src/openklant/components/klanten/api/schema.py
src/openklant/components/klanten/api/serializers.py
src/openklant/components/klanten/datamodel/models.py
src/openklant/components/klanten/openapi.yaml
src/openklant/components/klanten/resources.md
src/openklant/components/klanten/swagger2.0.json
src/openklant/utils/api_spec.py

Fixes: https://github.com/maykinmedia/open-klant/issues/18
TODO:

#18 Document OAS differences

---

src/openklant/components/klanten/api/serializers.py

see: https://github.com/maykinmedia/open-klant/pull/34#discussion_r791780416

:recycle: Make Klant.geverifieerd mutable for now

---

src/openklant/conf/api.py

to include ZaakContactMoment resource

:alien: Update Zaken API spec commit to version 1.1.0

---

requirements/ci.txt
requirements/dev.txt
requirements/test-tools.in

:heavy_minus_sign: Remove pyquery dependency

---

src/openklant/components/klanten/api/tests/test_auth.py

Some black/isort/flake8 love
This was breaking my other quick-fix PR's

Fixed CI code-quality issues

---

bootstrap.py
src/openklant/conf/base.py
src/openklant/conf/utils.py
src/openklant/utils/context_processors.py

Ik moest de twee variabelen toevoegen aan de public_settings in de context_processors. Daarnaast moest ik ook een functie aanmaken om de git_sha op te halen. Het is ook mogelijk om template tags te gebruiken om de versie en de git hash weer te geven in de template ipv via de settings aanroepen.

✨ [#51] Showing version & git hash on the home page

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/components/klantinteracties/api/schema.py
src/openklant/components/klantinteracties/api/urls.py
src/openklant/templates/legacy_index.html
src/openklant/templates/main.html
src/openklant/templates/master.html
src/openklant/urls.py

Fixes #116 
- added klantinteracties to the landing page
- removed bootstrap + jquery from the landing pages

:sparkles: [#116] removed bootstrap+jquery in landing page

---

.github/workflows/ci.yml

:construction_worker: [#115] added trivy

---

.github/workflows/ci.yml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
src/openklant/components/klantinteracties/migrations/0012_merge_0011_auto_20240209_0928_0011_rekeningnummer.py
src/openklant/conf/base.py
src/openklant/conf/dev.py
src/openklant/templates/account_blocked.html

Updated Django to be 4.2.0
- updated all packages to latest possible version
- updated django-axis configuration
- removed ddt-api-calls
- removed camilize override

:arrow_up: updated django to 4.2.0

---

.github/workflows/ci.yml
Dockerfile
INSTALL.rst

Updated python from 3.10 to 3.11 in tests and docker

:arrow_up: upgraded python from 3.10 to 3.11

---

src/openklant/components/contactgegevens/openapi.yaml
src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
src/openklant/components/klantinteracties/api/filterset/partijen.py
src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
src/openklant/components/klantinteracties/api/viewsets/partijen.py
src/openklant/components/klantinteracties/openapi.yaml
src/openklant/components/utils/filters.py
src/openklant/components/utils/schema.py
src/openklant/conf/api.py

Fixes #175
**Changes**
Expand queryset params now get generated on detail views.

:sparkles: [#175] added expand for detail endpoints in redoc

---

docker-compose.yml
src/openklant/templates/index.html
src/openklant/urls.py

Fixes: #188
Other settings removed in #190

[#188] remove unused notification settings

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
bin/generate_schema_for_component.sh
src/openklant/components/contactgegevens/openapi.yaml
src/openklant/components/klantinteracties/openapi.yaml

Partially fixes https://github.com/maykinmedia/open-api-framework/issues/17

[#17] add CI jobs to detect uncommitted OAS changes

---

src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
src/openklant/components/klantinteracties/openapi.yaml

Fixes #205
**Changes**
- change had_klantcontact help_text in betrokkeneSerializer

:memo: [#205] change had_klantcontact help_text in betrokkeneSerializer

---

requirements/ci.txt
requirements/dev.txt

Fixes #217 
**Changes**
updated webob from 1.8.7 to 1.8.8

:arrow_up: [#50] updated webob from 1.8.7 to 1.8.8

---

Dockerfile
package-lock.json

Fixes #50
**Changes**
Changed setuptools version in dockerfile
fixed npm issues

:art: [#50] upgrated setuptools in dockerfile and fixed npm issues

---

src/openklant/components/klantinteracties/admin/partijen.py
src/openklant/components/klantinteracties/models/tests/factories/partijen.py
src/openklant/components/klantinteracties/tests/test_admin.py

Fixes #229 
**Changes**
Fixes searching in the `Partij`en admin

[#229] fix partijen admin search

---

.github/workflows/oaf-check.yml

Fixes maykinmedia/open-api-framework#44 part

:construction_worker: add check open API framework action

---

CHANGELOG.rst
docs/installation/config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/fixtures/default_admin_index.json

Fixes the CI builds
**Changes**
See [OAF changelog](https://github.com/maykinmedia/open-api-framework/blob/main/CHANGELOG.rst#090-2024-11-11) (from `0.8.1`)

Update OAF version

---

src/openklant/components/klantinteracties/admin/digitaal_adres.py
src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
src/openklant/components/klantinteracties/api/tests/test_actoren.py
src/openklant/components/klantinteracties/api/tests/test_digitaal_adres.py
src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
src/openklant/components/klantinteracties/api/validators.py
src/openklant/components/klantinteracties/tests/test_admin.py
src/openklant/utils/tests/test_validators.py
src/openklant/utils/validators.py

Fixes #235
**Changes**
Improved the way we validate phonenumbers with the phonenumbers library

:art: [#235] improve the way we validate phonenumbers

---

src/openklant/urls.py

fixes: https://github.com/maykinmedia/open-api-framework/issues/79
**Changes**
Disables the admin nav sidebar

[maykinmedia/open-api-framework#79] disable admin nav sidebar

---

.github/workflows/quick-start.yml

Fixes [maykinmedia/open-api-framework#99]

[maykinmedia/open-api-framework#99] Add quick-start.yml

---

.github/ISSUE_TEMPLATE/prepare-release.md

Fixes maykinmedia/open-api-framework#107 partially
**Changes**
* Add prepare release template

:memo: [maykinmedia/open-api-framework#107] Add prepare release template

---

.github/workflows/oas-check.yml
bin/generate_schema_for_component.sh

Fixes maykinmedia/open-api-framework#115 partially
**Changes**
* Always run OAS check

👷 [maykinmedia/open-api-framework#115] Always run OAS check

---

src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
src/openklant/components/klantinteracties/api/tests/test_filters.py
src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
src/openklant/components/klantinteracties/openapi.yaml

[#212] Expand BetrokkeneSerializer with digitale_adressen

---

.github/workflows/ci.yml

and replaced it with a basic script

:construction_worker: Remove changed-files actions from CI

---

requirements/ci.txt
requirements/dev.txt

Should speed up the tests by ~2m

:arrow_up: Upgrade coverage to 7.7.0

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
package-lock.json
package.json
src/openklant/__init__.py
src/openklant/components/klantinteracties/openapi.yaml
src/openklant/conf/api.py

Small bugfix release to fix an issue which is blocking for KISS

🔖 Release version 2.6.1

---

src/openklant/components/klantinteracties/api/tests/partijen/test_partij_identificator.py
src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
src/openklant/components/klantinteracties/api/tests/test_rekeningnummers.py
src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
src/openklant/components/klantinteracties/api/viewsets/partijen.py
src/openklant/components/klantinteracties/api/viewsets/rekeningnummers.py

:bug: [#376] Fix query parameters on partij-identificatoren

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
package-lock.json
package.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/__init__.py
src/openklant/components/contactgegevens/openapi.yaml
src/openklant/components/klantinteracties/openapi.yaml
src/openklant/conf/api.py

:bookmark: Release 2.7.0

---

src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
src/openklant/components/klantinteracties/api/serializers/klantcontacten.py
src/openklant/components/klantinteracties/api/serializers/partijen.py
src/openklant/components/klantinteracties/api/serializers/rekeningnummers.py
src/openklant/components/klantinteracties/api/tests/partijen/test_categorie.py
src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py
src/openklant/components/klantinteracties/api/tests/partijen/test_partij_identificator.py
src/openklant/components/klantinteracties/api/tests/test_digitaal_adres.py
src/openklant/components/klantinteracties/api/tests/test_klantcontacten.py
src/openklant/components/klantinteracties/api/tests/test_rekeningnummers.py
src/openklant/components/klantinteracties/openapi.yaml

:hammer: [#240] Fix nullable fields non-required in creation endpoints

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/components/klantinteracties/api/filterset/actoren.py
src/openklant/components/klantinteracties/api/filterset/digitaal_adres.py
src/openklant/components/klantinteracties/api/filterset/internetaken.py
src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
src/openklant/components/klantinteracties/api/filterset/partijen.py
src/openklant/components/klantinteracties/api/serializers/digitaal_adres.py
src/openklant/components/klantinteracties/openapi.yaml

:memo: [#341] Fix help_text field in FilterSet

---

src/openklant/components/klantinteracties/api/serializers/partijen.py
src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py

:hammer: [#401] Fix PATCH requests for digitaleAdressen and rekeningnummers

---

src/openklant/components/klantinteracties/api/schema.py
src/openklant/components/klantinteracties/openapi.yaml

:memo: [#363] Update documentation for PartijIdentificator

---

src/openklant/components/klantinteracties/api/filterset/digitaal_adres.py
src/openklant/components/klantinteracties/api/filterset/klantcontacten.py
src/openklant/components/klantinteracties/api/tests/test_filters.py
src/openklant/components/klantinteracties/openapi.yaml

Fixes #342 
**Changes**
- adds klantcontact betrokkene partij identificator filters
- adds betrokkene partij identificator filters
- adds digitale adres partij identificator filters

:sparkles: [#342] add klantcontact partij identificator filters

---

docs/installation/config/admin_configuration.rst

:memo: [#408] Fix notificaties docs

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
package-lock.json
package.json
src/openklant/__init__.py
src/openklant/components/klantinteracties/openapi.yaml
src/openklant/conf/api.py

:bookmark: Release 2.8.0

---

src/openklant/accounts/tests/test_csrf.py
src/openklant/accounts/views/csrf.py

Fixes #418 
**Changes**
changed the redirect url and added test for it

:bug: [#418] fix NoReverseMatch error and added tests

---

.github/workflows/ci.yml
INSTALL.rst
docs/installation/config/env_configuration.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/accounts/management/commands/createinitialsuperuser.py
src/openklant/accounts/tests/test_oidc.py
src/openklant/components/klantinteracties/api/tests/partijen/test_partij.py
src/openklant/components/klantinteracties/api/tests/partijen/test_partij_identificator.py
src/openklant/components/klantinteracties/models/tests/test_partijen.py
src/openklant/components/klantinteracties/tests/test_admin.py
src/openklant/conf/base.py
src/openklant/conf/ci.py
src/openklant/scss/admin/_admin_theme.scss
src/openklant/templates/admin/base_site.html

:white_check_mark: [#426] Upgrade to Django 5.2 and introduce connection pooling

---

docs/installation/config/env_configuration.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/conf/base.py

Upgrade `open-api-framework` to 0.10.3
Upgrade `notifications-api-common` to 0.7.3

:arrow_up: Upgrade dependencies

---

docs/manual/logging.rst
src/openklant/components/contactgegevens/api/viewset.py
src/openklant/components/klantinteracties/api/viewsets/actoren.py
src/openklant/components/klantinteracties/api/viewsets/digitaal_adres.py
src/openklant/components/klantinteracties/api/viewsets/internetaken.py
src/openklant/components/klantinteracties/api/viewsets/klantcontacten.py
src/openklant/components/klantinteracties/api/viewsets/partijen.py
src/openklant/components/klantinteracties/api/viewsets/rekeningnummers.py

:sparkles: [#445] Add logging events for operations on all API endpoints

---

CHANGELOG.rst
README.rst
package-lock.json
package.json
pyproject.toml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openklant/__init__.py

:bookmark: Release 2.10.0

---

README.rst

:memo: [#191] add contactgegevens API links to README

---

src/openklant/conf/base.py
src/openklant/setup.py

Fixes maykinmedia/open-api-framework#179
**Changes**

 :sparkles: [maykinmedia/open-api-framework#179] Monkeypatch requests to set default timeout

---

CHANGELOG.rst
README.rst
migration/cassettes/test_natuurlijk_persoon_bsn_with_leading_zeroes.yaml
migration/cassettes/test_natuurlijk_persoon_invalid_bsn.yaml
package-lock.json
package.json
pyproject.toml
src/openklant/__init__.py
src/openklant/migration/v1/data.py
src/openklant/tests/test_migrate.py

Fixes #495
**Changes**
* Release version 2.12.1

:bookmark: [#495] Release version 2.12.1

---

bin/docker_start.sh

Fixes maykinmedia/open-api-framework#85
**Changes**

:sparkles: [maykinmedia/open-api-framework#85] set UWSGI_THREADS to 4

---

src/openklant/accounts/apps.py
src/openklant/accounts/signals.py
src/openklant/accounts/tests/test_signals.py

:bug: [#486] Ensure default_admin_index.json is loaded via signal

---

docs/installation/migration.rst

Fixes #501
**Changes**
* Mention migrate_to_v2_phonenumbers command in docs

:memo: [#501] Mention migrate_to_v2_phonenumbers command in docs

---

src/openklant/scss/_settings.scss

:fire: Remove css root from _settings.scss

---

src/openklant/scss/_app.scss
src/openklant/scss/_settings.scss
src/openklant/scss/screen.scss

:bug: [#508] Fix landing page css

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:arrow_up: [#489] update notifications-api-common to 0.9.0
